package co.edu.uniajc.model;
// Generated 20/04/2019 10:28:16 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "banco")
public class Banco implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_banco")
	private Integer idBanco;
	
	@Column(name = "nit")
	private String nit;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "direccion")
	private String direccion;
	
	@Column(name = "telefono")
	private String telefono;
	
//	@Column(name = "cuentas")
//	private Set cuentas = new HashSet(0);
//	
//	@Column(name = "cajeros")
//	private Set cajeros = new HashSet(0);

	public Banco() {
	}

	public Banco(String nit, String nombre) {
		this.nit = nit;
		this.nombre = nombre;
	}

	public Banco(String nit, String nombre, String direccion, String telefono) {
		this.nit = nit;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
//		this.cuentas = cuentas;
//		this.cajeros = cajeros;
	}

	public Integer getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(Integer idBanco) {
		this.idBanco = idBanco;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

//	public Set getCuentas() {
//		return this.cuentas;
//	}
//
//	public void setCuentas(Set cuentas) {
//		this.cuentas = cuentas;
//	}
//
//	public Set getCajeros() {
//		return this.cajeros;
//	}
//
//	public void setCajeros(Set cajeros) {
//		this.cajeros = cajeros;
//	}

}
