package co.edu.uniajc.model;
// Generated 20/04/2019 10:28:16 AM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cajero generated by hbm2java
 */
@Entity
@Table (name = "cajero")
public class Cajero implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_cajero")
	private Integer idCajero;
	
	@JoinColumn(name = "id_banco", nullable = true, updatable = false)
    @ManyToOne(fetch = FetchType.EAGER)
	private Banco banco;
	
	@Column(name = "saldo")
	private BigDecimal saldo;
	
	@Column(name = "ubicacion")
	private String ubicacion;
	
	@Column(name = "ind_servicio")
	private int indServicio;
	
	public Cajero() {
	}

	public Cajero(Banco banco, BigDecimal saldo, String ubicacion, int indServicio) {
		this.banco = banco;
		this.saldo = saldo;
		this.ubicacion = ubicacion;
		this.indServicio = indServicio;
		

	}

	public Integer getIdCajero() {
		return this.idCajero;
	}

	public void setIdCajero(Integer idCajero) {
		this.idCajero = idCajero;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public int getIndServicio() {
		return this.indServicio;
	}

	public void setIndServicio(int indServicio) {
		this.indServicio = indServicio;
	}

	
}
